services:
  discord-bot:
    build: discord
    container_name: discord-bot
    restart: unless-stopped
    environment:
      - DISCORD_API_KEY=${DISCORD_API_KEY}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
      - WEBHOOK_URL=${WEBHOOK_URL}

  flask:
    build: flask
    container_name: flask
    restart: unless-stopped
    ports:
      - 4200:${IMAP_PASS}
    environment:
      - IMAP_HOST=${IMAP_HOST}
      - IMAP_PORT=${IMAP_PORT}
      - IMAP_USER=${IMAP_USER}
      - IMAP_PASS=${IMAP_PASS}
