services:
  webservice:             
    build: webservice
    container_name: webservice
    restart: unless-stopped
    ports:
      - 4200:${PORT}
    environment:
      - IMAP_HOST=${IMAP_HOST}
      - IMAP_PORT=${IMAP_PORT}
      - IMAP_USER=${IMAP_USER}
      - IMAP_PASS=${IMAP_PASS}
      - PORT=${PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  discord-bot:
    build: discordbot
    container_name: discord-bot
    restart: unless-stopped
    ports:
      - 4210:${PORT2}
    environment:
      - DISCORD_API_KEY=${DISCORD_API_KEY}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - PORT2=${PORT2}